// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlsmwdiuqockrvekqpdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsc213ZGl1cW9ja3J2ZWtxcGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0OTM0MTEsImV4cCI6MjA0OTA2OTQxMX0.tAFHq3ECAcr7pwrk7oUcK_PQ81xoyX2gU72WAlHLMzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);